<a href="https://colab.research.google.com/github/edik06031-rgb/DTA_2026/blob/main/HW/numpy_homework_01_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [23]:
import numpy as np

# Твій код:


# Створюємо масив температур
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])

# Виводимо масив
print("Масив температур:", temps)


# Інформація про масив
print(f"Кількість вимірів (ndim):", temps.ndim)
print("Форма масиву (shape):", temps.shape)
print("Кількість елементів (size):", temps.size)
print("Тип даних (dtype):", temps.dtype)

# Основні статистики
print(f"Мінімальна температура:", temps.min())
print("Максимальна температура:", temps.max())
print("Середньорічна температура:", round(temps.mean(), 1))


Масив температур: [-5 -4  2 10 17 21 23 22 16  9  2 -3]
Кількість вимірів (ndim): 1
Форма масиву (shape): (12,)
Кількість елементів (size): 12
Тип даних (dtype): int64
Мінімальна температура: -5
Максимальна температура: 23
Середньорічна температура: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [24]:
# Твій код:
import numpy as np

# Створюємо матрицю планових продажів 3x4
plan = np.full((3, 4), 50)

# Виводимо матрицю
print("Матриця plan:\n",plan)

# Виводимо форму та кількість елементів
print("Форма матриці:", plan.shape)
print("Кількість елементів:", plan.size)

# Створюємо матрицю бонусів із нулів
bonus = np.zeros((3, 4))

# Виводимо матрицю bonus
print("Матриця bonus:\n",bonus)

# Додаємо матриці
result = plan + bonus

# Виводимо результат
print("Сума plan + bonus:\n",result)


Матриця plan:
 [[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
Форма матриці: (3, 4)
Кількість елементів: 12
Матриця bonus:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Сума plan + bonus:
 [[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [25]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
import numpy as np



# 1. Продажі першого тижня                   # це я тренувався з рядками, тому закоментував                                              #другий print
print("1.Перший тиждень:\n",sales[:7])       # другий print як другий варіант відповіді
#print(sales[:7])

# 2. Продажі другого тижня
print("\n2.Другий тиждень:\n",sales[7:])
#print(sales[7:])

# 3. Продажі у вихідні
print("\n3.Вихідні дні:\n",sales[[5, 6, 12, 13]])
#print(sales[[5, 6, 12, 13]])

# 4. Продажі через день (непарні дні)
print("\n4.Непарні дні:\n",sales[::2])
#print(sales[::2])

# 5. Масив у зворотному порядку
print("\n5.Масив у зворотному порядку:\n",sales[::-1])
#print(sales[::-1])


1.Перший тиждень:
 [320 415 290 480 350 620 580]

2.Другий тиждень:
 [310 440 305 510 370 650 595]

3.Вихідні дні:
 [620 580 650 595]

4.Непарні дні:
 [320 290 350 580 440 510 650]

5.Масив у зворотному порядку:
 [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [26]:
grades = np.array([
    [85, 72, 91, 78, 88], # Олена
    [63, 88, 74, 95, 70], # Максим
    [90, 65, 82, 70, 94], # Аня
    [75, 80, 68, 85, 79], # Богдан
])

# Твій код:
print("1.Оцінки Олени:\n",grades[0,:])
print("2.Оцінки всіх студентів 3_й предмет:\n",grades[:,2])
print("3.Підматриця оцінки Максима та Ані:\nМаксим:",grades[1,:])
print("Аня :",grades[2,:])
print("4.Оцінки останнього студента 'Богдан' з останнього предмету :",grades[3,4])


1.Оцінки Олени:
 [85 72 91 78 88]
2.Оцінки всіх студентів 3_й предмет:
 [91 74 82 68]
3.Підматриця оцінки Максима та Ані:
Максим: [63 88 74 95 70]
Аня : [90 65 82 70 94]
4.Оцінки останнього студента 'Богдан' з останнього предмету : 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [27]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
import numpy as np

# Курс долара
rate = 41.5

# 1. Переведення в гривні
prices_uah = np.round(prices_usd * rate, 2)

# 2. Нарахування ПДВ 20%
prices_vat = np.round(prices_uah * 1.2, 2)

# 3. Мінімальна, максимальна, середня ціна
min_price = prices_vat.min()
max_price = prices_vat.max()
avg_price = round(prices_vat.mean(), 2)

# 4. Загальна сума кошика
total = round(prices_vat.sum(), 2)

# Виведення результатів
print("Ціни у доларах:",prices_usd)
print("\n1.Ціни у гривнях:",prices_uah)
print("\n2.Ціни з ПДВ 20%:",prices_vat)


print("\n3.1. Мінімальна ціна:", min_price)
print("\n3.2. Максимальна ціна:", max_price)
print("\n3.3. Середня ціна:", avg_price)
#print("\n3.3. Середня ціна:", round(prices_vat.mean(), 2))
print("\n4. Загальна вартість кошика:", total)

Ціни у доларах: [ 15.99  42.5    8.   125.    33.75  67.2    9.99]

1.Ціни у гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]

2.Ціни з ПДВ 20%: [ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]

3.1. Мінімальна ціна: 398.4

3.2. Максимальна ціна: 6225.0

3.3. Середня ціна: 2151.57

4. Загальна вартість кошика: 15061.0


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [28]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
total = quantity * cost_each
print("1.загальну вартість кожного товару на складі : \n",total)
warehouse_total = total.sum()
print("\n2.загальну вартість всього складу :", warehouse_total)
max_index = np.argmax(total)
print("\n3.товар з найбільшою сумарною вартістю : ",(names[max_index]))
min_index = np.argmin(total)
print("\n4.товар з найменшою сумарною вартістю : ",(names[min_index]))
print("\n5.Середня вартість:",round(total.mean(), 2))



1.загальну вартість кожного товару на складі : 
 [ 30000  81000  13500 171000  28500  24000  45000]

2.загальну вартість всього складу : 393000

3.товар з найбільшою сумарною вартістю :  Монітор

4.товар з найменшою сумарною вартістю :  Зошит

5.Середня вартість: 56142.86


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [29]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
#  всі замовлення, виконані вчасно (≤ 30 хв)
on_time = delivery_time[delivery_time <= 30]
print("1.Всі замовлення, виконані вчасно (≤ 30 хв):\n",on_time)

#  всі запізнілі замовлення (> 30 хв)
out_time = delivery_time[delivery_time > 30]
print("\n2.Всі запізнілі замовлення (> 30 хв):\n",out_time)

# Kількість вчасних
on_time_count = on_time.size
print("\n3.Kількість вчасних :",on_time_count)

# Kількість запізнілих
out_time_count = out_time.size
print("\n3.1. Kількість запізнілих:",out_time_count)

# відсоток запізнілих замовлень (округли до 1 знаку)
out_time_percent = round((out_time_count / delivery_time.size) * 100, 1)
print("\n4.Bідсоток запізнілих замовлень: ",out_time_percent,"%" )

# На скільки хвилин запізнювалися замовлення
delay = out_time - 30
print(" На скільки хвилин запізнювалися замовлення? ",delay,"хвилин")

# середня затримка серед запізнілих замовлень
avg_out_time = round(delay.mean(), 1)
print("\n5.Cередня затримка серед запізнілих замовлень:",avg_out_time,'хвилин')




1.Всі замовлення, виконані вчасно (≤ 30 хв):
 [22 28 19 27 24 26 18 29 23 20]

2.Всі запізнілі замовлення (> 30 хв):
 [35 41 55 33 48 31 52 38 44 36]

3.Kількість вчасних : 10

3.1. Kількість запізнілих: 10

4.Bідсоток запізнілих замовлень:  50.0 %
 На скільки хвилин запізнювалися замовлення?  [ 5 11 25  3 18  1 22  8 14  6] хвилин

5.Cередня затримка серед запізнілих замовлень: 11.3 хвилин


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [30]:


# Твій код:
import numpy as np

# Генерація випадкових продажів
np.random.seed(42)

# Продажі за місяць
daily = np.random.randint(100, 900, size=30)
print("\n1.Продажі за місяць:",daily)

# Середній продаж за місяць
average = daily.mean()
print("\n2.Середній продаж за місяць:",round(average, 2))

# 1. Дні з продажами вище середнього
above_avg = daily[daily > average]
print("\n3.Продажі вище середнього:",above_avg)

# 2. Кількість таких днів
count_above = above_avg.size
print("\n4.Кількість днів вище середнього:",count_above)

# 3. Створення масиву статусів
status = np.where(
    daily > average,
    'Гарний день',
    'Звичайний день'
)
print("\nПерші 10 днів:")
for i in range(10):
    print(f"День {i+1}: {daily[i]} -> {status[i]}")




1.Продажі за місяць: [202 535 370 206 171 800 120 714 221 566 314 430 558 187 472 199 763 230
 761 408 869 443 591 513 485 291 376 260 559 413]

2.Середній продаж за місяць: 434.23

3.Продажі вище середнього: [535 800 714 566 558 472 763 761 869 443 591 513 485 559]

4.Кількість днів вище середнього: 14

Перші 10 днів:
День 1: 202 -> Звичайний день
День 2: 535 -> Гарний день
День 3: 370 -> Звичайний день
День 4: 206 -> Звичайний день
День 5: 171 -> Звичайний день
День 6: 800 -> Гарний день
День 7: 120 -> Звичайний день
День 8: 714 -> Гарний день
День 9: 221 -> Звичайний день
День 10: 566 -> Гарний день


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [31]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
import numpy as np

# 1. Перетворення у матрицю 6×4
matrix = hourly.reshape(6, 4)

print("1.Матриця 6x4:\n",matrix)

# 2. Сума продажів у кожному 4-годинному блоці
row_sums = matrix.sum(axis=1)

print("\n2.Сума по рядках:",row_sums)

# 3. Сортування масиву за зростанням
sorted_hourly = np.sort(hourly)

print("\n3.Відсортований масив:\n",sorted_hourly)

# 4. Індекси годин, відсортованих за продажами
sorted_indices = np.argsort(hourly)

print("\n4.Індекси після сортування:\n",sorted_indices)

# 5. Топ-3 найпродуктивніших години
top3_hours = np.argsort(hourly)[-3:]

print("\nТоп-3 години:",top3_hours)


1.Матриця 6x4:
 [[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]

2.Сума по рядках: [ 28  66 235 240 257 112]

3.Відсортований масив:
 [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]

4.Індекси після сортування:
 [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]

Топ-3 години: [19 12 18]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [32]:
# Твій код:
import numpy as np

# 1. Фіксуємо seed
np.random.seed(99)

# 2. Вік клієнтів
ages = np.random.randint(18, 66, size=50)
print("\nСередній вік клієнтів:", round(average_age, 2))

# 3. Оцінки задоволеності
scores = np.random.normal(loc=7, scale=1.5, size=50)
print("\nСередня оцінка задоволеності:", round(average_score, 2))

# Округлення до 1 знаку
scores = np.round(scores, 1)

# 4. Обрізання значень у межах 1–10
scores = np.clip(scores, 1, 10)

# 5. Обчислення показників
average_age = ages.mean()
average_score = scores.mean()

satisfied_count = np.sum(scores >= 8)

print("\nКількість задоволених клієнтів:", satisfied_count)

satisfied_percent = satisfied_count / len(scores) * 100

print("\nВідсоток задоволених:", round(satisfied_percent, 2), "%")









Середній вік клієнтів: 41.8

Середня оцінка задоволеності: 6.87

Кількість задоволених клієнтів: 10

Відсоток задоволених: 20.0 %


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [33]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [34]:
# # Твій код:
import numpy as np

print('\n--- Загальна статистика ---')

# 1. Загальна виручка
total_sales = sales_56.sum()
print(f'\nЗагальна виручка за 56 днів: {total_sales}')

# 2. Середньоденна виручка
average_sales = sales_56.mean()
print(f'\nСередньоденна виручка: {average_sales:.2f}')

# 3. Мінімальний та максимальний продаж
min_sales = sales_56.min()
print(f'\nМінімальний денний продаж: {min_sales}')
max_sales = sales_56.max()
print(f'\nМаксимальний денний продаж: {max_sales}')

# 4. Стандартне відхилення
std_sales = sales_56.std()
print(f'\nСтандартне відхилення: {std_sales:.2f}')












--- Загальна статистика ---

Загальна виручка за 56 днів: 31819

Середньоденна виручка: 568.20

Мінімальний денний продаж: 222

Максимальний денний продаж: 1072

Стандартне відхилення: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [42]:
# Твій код:
import numpy as np

# # Дані — не змінюй
# np.random.seed(2024)

# base = np.random.randint(200, 800, 56)

# weekend_boost = np.array([
#     1 if i % 7 in [5, 6] else 0
#     for i in range(56)
# ])

# sales_56 = (
#     base + weekend_boost * np.random.randint(100, 300, 56)
# ).astype(int)

# 1. Перетворення у матрицю 8×7
weeks = sales_56.reshape(8, 7)

print("Матриця 8x7:\n",weeks)


# 2. Виручка кожного тижня
weekly_sales = weeks.sum(axis=1)

print("\nВиручка по тижнях:",weekly_sales)


# 3. Найкращий тиждень
best_week_index = np.argmax(weekly_sales)

best_week_sum = weekly_sales[best_week_index]

print(f"\nНайкращий тиждень: {best_week_index + 1}")

print(f"Сума продажів: {best_week_sum}")

# 4. Середньоденна виручка по днях тижня
daily_average = weeks.mean(axis=0)

print("\nСередня виручка по днях тижня:",(np.round(daily_average, 2)))

# 5. Найприбутковіший день тижня
best_day = np.argmax(daily_average)

print(f"\nНайприбутковіший день тижня: {best_day}")

Матриця 8x7:
 [[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]

Виручка по тижнях: [4555 3921 3563 3546 5036 3300 4228 3670]

Найкращий тиждень: 5
Сума продажів: 5036

Середня виручка по днях тижня: [520.38 455.5  565.88 607.75 463.75 629.75 734.38]

Найприбутковіший день тижня: 6


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [44]:
# Твій код:
import numpy as np

# # Дані — не змінюй
# np.random.seed(2024)

# base = np.random.randint(200, 800, 56)

# weekend_boost = np.array([
#     1 if i % 7 in [5, 6] else 0
#     for i in range(56)
# ])

# sales_56 = (
#     base + weekend_boost * np.random.randint(100, 300, 56)
# ).astype(int)

# 1. Слабкі та сильні дні
weak_days = sales_56 < 400
strong_days = sales_56 > 700

# Кількість
weak_count = np.sum(weak_days)
strong_count = np.sum(strong_days)

print(f"Кількість слабких днів: {weak_count}")

print(f"Кількість сильних днів: {strong_count}")

# 2. Середня виручка
weak_average = sales_56[weak_days].mean()
strong_average = sales_56[strong_days].mean()

print(f"\nСередня виручка у слабкі дні: {weak_average:.2f}")

print(f"Середня виручка у сильні дні: {strong_average:.2f}")

# 3. Створення labels через np.where()
labels = np.where(sales_56 < 400,'Слабкий',np.where( sales_56 > 700,
 'Сильний','Нормальний'))

# 4. Перші 14 днів
print("\nПерші 14 днів:")

for i in range(14):
    print(
        f"День {i}: продажі = {sales_56[i]}, мітка = {labels[i]}"
    )


Кількість слабких днів: 12
Кількість сильних днів: 19

Середня виручка у слабкі дні: 302.00
Середня виручка у сильні дні: 785.16

Перші 14 днів:
День 0: продажі = 706, мітка = Сильний
День 1: продажі = 739, мітка = Сильний
День 2: продажі = 748, мітка = Сильний
День 3: продажі = 646, мітка = Нормальний
День 4: продажі = 383, мітка = Слабкий
День 5: продажі = 556, мітка = Нормальний
День 6: продажі = 777, мітка = Сильний
День 7: продажі = 427, мітка = Нормальний
День 8: продажі = 274, мітка = Слабкий
День 9: продажі = 522, мітка = Нормальний
День 10: продажі = 680, мітка = Нормальний
День 11: продажі = 708, мітка = Сильний
День 12: продажі = 465, мітка = Нормальний
День 13: продажі = 845, мітка = Сильний


---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
